import asyncio
import os
import subprocess
import edge_tts
import static_ffmpeg

ffmpeg_exe, _ = static_ffmpeg.run.get_or_fetch_platform_executables_else_raise()

output_dir = r"C:\Users\atiqu\.gemini\antigravity\scratch\ai-news-weekly\public"
os.makedirs(output_dir, exist_ok=True)

raw_mp3 = os.path.join(output_dir, "raw_voiceover.mp3")
mastered_wav = os.path.join(output_dir, "voiceover.wav")

script_text = """Anthropic just quietly killed Claude Opus 5.2 before it even launched. And the reason why is sending shockwaves through the AI frontier: they aren't releasing 5.2 at all. They just leapfrogged straight to Claude Opus 5.5.

For the past three weeks, developers tracked internal references pointing to an upcoming Opus 5.2 drop. But in the last twenty-four hours, production checkpoint leaks confirmed a massive strategy pivot. Anthropic determined that their newest model's jump in spatial reasoning and autonomous code execution was too massive for an incremental 0.2 version.

It is codenamed 'claude-wafer-eap'—and leaks claim it is dropping this Tuesday.

And the leaked outputs circulating among early access testers explain exactly why. Look at this generation from researcher Harshith. This is a full three-dimensional, autonomous Waymo Jaguar I-PACE—rendered in pure code inside Claude Code.

Notice the physical lidar arrays, the camera mounts, and exact vehicle geometry. In Opus 5, running a multi-step generation of this depth cost over fifty dollars. Opus 5.5 reportedly delivered this exact model for twenty-seven dollars. That is a forty-six percent real-world cost collapse on heavy engineering tasks.

And it does not stop at autonomous vehicles. Look at this architectural modern villa generated by Srikanth Valluri—pure Three.js with ambient glass shaders, photorealistic refractions, and clean state handling. Followed by a full isometric town simulation featuring dynamic truck movement, procedural foliage, and consistent atmospheric lighting across the entire canvas.

With hype reaching a fever pitch, community scrutiny has hit an all-time high. When a viral clip claimed Opus 5.5 generated a complex city driving engine, developers reverse-engineered the frames within hours—proving the video was stolen directly from a preexisting YouTube render. In this frontier war, every single claim is being audited down to the pixel.

The real danger for competitors isn't just intelligence—it's economics. Leaked pricing reveals Anthropic slashed input rates to four dollars, output to twenty dollars, and cut prompt cache reads by a staggering sixty percent.

That puts Opus 5.5 directly on a collision course with OpenAI's upcoming GPT-6 Sol. The AI race didn't slow down. It just moved to warp speed."""

async def generate_voiceover():
    print("Generating raw TTS audio via msedge-tts (en-US-BrianMultilingualNeural)...")
    # Rate: +0%, Pitch: +0Hz
    communicate = edge_tts.Communicate(
        text=script_text,
        voice="en-US-BrianMultilingualNeural",
        rate="+0%",
        pitch="+0Hz"
    )
    await communicate.save(raw_mp3)
    print(f"Raw MP3 saved to {raw_mp3} ({os.path.getsize(raw_mp3)} bytes)")

    print("Mastering audio via FFmpeg loudnorm to YouTube broadcast standard (-16 LUFS)...")
    cmd = [
        ffmpeg_exe,
        "-y",
        "-i", raw_mp3,
        "-af", "loudnorm=I=-16:TP=-1.5:LRA=11",
        "-ar", "48000",
        "-ac", "2",
        mastered_wav
    ]
    subprocess.run(cmd, check=True)
    print(f"Broadcast mastered WAV saved to {mastered_wav} ({os.path.getsize(mastered_wav)} bytes)")

if __name__ == "__main__":
    asyncio.run(generate_voiceover())
